name: Extension Testing Workflow

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'extension/**'
env:
  WORKING_DIRECTORY: ./extension
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: NPM Install
        uses: bahmutov/npm-install@v1
      - name: Run Unit Tests and Submit Coverage
        run: |
          yarn test:unit --coverage
          bash <(curl -s https://codecov.io/bash)
        working-directory: ${{env.WORKING_DIRECTORY}}
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: NPM Install
        uses: bahmutov/npm-install@v1
      - name: Lint
        run: yarn lint
        working-directory: ${{env.WORKING_DIRECTORY}}
  checkChangelog:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: Check Changelog
        run: npx simsala check --pending-path ./extension/changes
